// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdmOJD3ng_06sUI7yN5JabJuWIJdM0uUo',
    appId: '1:295919767300:web:3481a5a900197487d24a51',
    messagingSenderId: '295919767300',
    projectId: 'ois-movies',
    authDomain: 'ois-movies.firebaseapp.com',
    storageBucket: 'ois-movies.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4CcSFyPSci-H3dT0ewguYXUU-W-L0Tew',
    appId: '1:295919767300:android:10fb8f89d4d02de5d24a51',
    messagingSenderId: '295919767300',
    projectId: 'ois-movies',
    storageBucket: 'ois-movies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi5905iobth6tvvHpA7lF6ZPY8fKzohyc',
    appId: '1:295919767300:ios:621d4f382c511423d24a51',
    messagingSenderId: '295919767300',
    projectId: 'ois-movies',
    storageBucket: 'ois-movies.appspot.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi5905iobth6tvvHpA7lF6ZPY8fKzohyc',
    appId: '1:295919767300:ios:621d4f382c511423d24a51',
    messagingSenderId: '295919767300',
    projectId: 'ois-movies',
    storageBucket: 'ois-movies.appspot.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdmOJD3ng_06sUI7yN5JabJuWIJdM0uUo',
    appId: '1:295919767300:web:ee7d3f2fea6f1159d24a51',
    messagingSenderId: '295919767300',
    projectId: 'ois-movies',
    authDomain: 'ois-movies.firebaseapp.com',
    storageBucket: 'ois-movies.appspot.com',
  );

}